agent: drq
max_traj_length: 100
batch_size: 256
cta_ratio: 2
discount: 0.97

max_steps: 1000000
replay_buffer_capacity: 200000

random_steps: 0
training_starts: 100
steps_per_update: 50

log_period: 10
eval_period: 2000

# "resnet" for ResNet10 from scratch and "resnet-pretrained" for frozen ResNet10 with pretrained weights
encoder_type: resnet-pretrained
demo_path: null
checkpoint_period: 0
buffer_period: 0

eval_checkpoint_step: 0
eval_n_trajs: 5

image_keys: []
classifier_keys: []
proprio_keys: []

# "single-arm-learned-gripper", "dual-arm-learned-gripper" for with learned gripper, 
# "single-arm-fixed-gripper", "dual-arm-fixed-gripper" for without learned gripper (i.e. pregrasped)
setup_mode: single-arm-fixed-gripper
