defaults:
  - default
  - _self_

classifier:
  _target_: serl_launcher.networks.reward_classifier.load_classifier_func
  image_keys: [wrist_1, wrist_2]
  checkpoint_path: ${abspath:classifier_ckpt/}

image_keys: [wrist_1, wrist_2]
proprio_keys: [tcp_pose, tcp_vel, tcp_force, tcp_torque, gripper_pose]
buffer_period: 1000
checkpoint_period: 5000
steps_per_update: 50
encoder_type: resnet-pretrained
setup_mode: single-arm-fixed-gripper
